/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module autoTester_7 (
    input clk,
    input rst,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] solution,
    output reg simError
  );
  
  
  
  localparam A_ROM = 128'h000a0040000580172e2b000601000000;
  
  localparam B_ROM = 128'h00050018000400014563800501000004;
  
  localparam ALUFN_ROM = 48'h001823616cf5;
  
  localparam SOLUTION_ROM = 128'h000f00280050c00b0423800300010001;
  
  reg [3:0] M_idx_d, M_idx_q = 1'h0;
  
  always @* begin
    M_idx_d = M_idx_q;
    
    if (M_idx_q == 4'h8) begin
      M_idx_d = 4'h0;
    end
    a = A_ROM[(M_idx_q)*16+15-:16];
    b = B_ROM[(M_idx_q)*16+15-:16];
    alufn = ALUFN_ROM[(M_idx_q)*6+5-:6];
    solution = SOLUTION_ROM[(M_idx_q)*16+15-:16];
    simError = M_idx_q[0+0-:1];
    M_idx_d = M_idx_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_idx_q <= 1'h0;
    end else begin
      M_idx_q <= M_idx_d;
    end
  end
  
endmodule
