/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [1-1:0] M_buttondetector_out;
  reg [1-1:0] M_buttondetector_in;
  edge_detector_2 buttondetector (
    .clk(clk),
    .in(M_buttondetector_in),
    .out(M_buttondetector_out)
  );
  
  wire [1-1:0] M_buttoncond_out;
  reg [1-1:0] M_buttoncond_in;
  button_conditioner_3 buttoncond (
    .clk(clk),
    .in(M_buttoncond_in),
    .out(M_buttoncond_out)
  );
  
  wire [16-1:0] M_aluMachine_out;
  wire [3-1:0] M_aluMachine_zvn;
  reg [16-1:0] M_aluMachine_a;
  reg [16-1:0] M_aluMachine_b;
  reg [6-1:0] M_aluMachine_alufn;
  alu_4 aluMachine (
    .a(M_aluMachine_a),
    .b(M_aluMachine_b),
    .alufn(M_aluMachine_alufn),
    .out(M_aluMachine_out),
    .zvn(M_aluMachine_zvn)
  );
  
  wire [16-1:0] M_inputMachine_a_out;
  wire [16-1:0] M_inputMachine_b_out;
  wire [6-1:0] M_inputMachine_alufn_out;
  wire [1-1:0] M_inputMachine_displayState;
  reg [16-1:0] M_inputMachine_input_switches;
  reg [1-1:0] M_inputMachine_enter_button;
  inputSM_5 inputMachine (
    .clk(clk),
    .rst(rst),
    .input_switches(M_inputMachine_input_switches),
    .enter_button(M_inputMachine_enter_button),
    .a_out(M_inputMachine_a_out),
    .b_out(M_inputMachine_b_out),
    .alufn_out(M_inputMachine_alufn_out),
    .displayState(M_inputMachine_displayState)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_buttoncond_in = io_button[1+0-:1];
    M_buttondetector_in = M_buttoncond_out;
    M_inputMachine_enter_button = M_buttondetector_out;
    M_inputMachine_input_switches[0+7-:8] = io_dip[0+0+7-:8];
    M_inputMachine_input_switches[8+7-:8] = io_dip[8+0+7-:8];
    if (M_inputMachine_displayState) begin
      M_aluMachine_a = M_inputMachine_a_out;
      M_aluMachine_b = M_inputMachine_b_out;
      M_aluMachine_alufn = M_inputMachine_alufn_out;
      io_led[0+0+7-:8] = M_aluMachine_out[0+7-:8];
      io_led[8+0+7-:8] = M_aluMachine_out[8+7-:8];
      io_led[16+0+2-:3] = M_aluMachine_zvn;
    end else begin
      M_aluMachine_a = 16'h0000;
      M_aluMachine_b = 16'h0000;
      M_aluMachine_alufn = 6'h00;
      io_led = 24'h000000;
    end
  end
endmodule
